name: scotus-metalang
channels:
  - nvidia
  - conda-forge
dependencies:
  # pyg will break pytorch gpu installation if pytorch isn't higher in list
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - cupy
  - huggingface::transformers
  - ipywidgets
  - jaxtyping
  - jsonlines
  - jupyterlab
  - networkx  # Graph networks for HiPool
  - pandas
  - pip
  - python
  - python-dotenv
  - pyg::pyg  # PyTorch Geometric for HiPool
  - spacy=3.4.3
  - spacy-transformers
  - tokenizers
  - typeguard
  - pip:
    - spacy-lookups-data