name: scotus-metalang
channels:
  - conda-forge
  - nvidia
dependencies:
  - cupy
  - huggingface::transformers
  - ipywidgets
  - jupyterlab
  - pandas
  - pip
  - python
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - spacy
  - spacy-transformers
  - pip:
    - jsonlines
    - spacy-lookups-data
    - tokenizers
    #- tokenizers>=0.11.1,!=0.11.3,<0.13