name: scotus-metalang
channels:
  - nvidia
  - conda-forge
dependencies:
  # pyg will break pytorch gpu installation if pytorch isn't higher in list
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - aiohttp
  - cupy
  - h5py
  - huggingface::transformers
  - ipywidgets
  - jsonlines
  - jupyterlab
  - networkx  # Graph networks for HiPool
  - pandas=2.1.0 # Pyg collision with pandas' 2.2.1 numexpr requirement
  - pip
  - pytables # For pandas .to_hdf
  - python
  - python-dotenv
  - pyg::pyg  # PyTorch Geometric for HiPool
  - seaborn
  - spacy=3.4.3
  - spacy-transformers
  - tensorboard
  - tokenizers
  - typeguard
  - pip:
    - jaxtyping
    - torcheval
    - snakeviz
    - spacy-lookups-data